'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { SiteHeader } from '../../components/site-header';
import { useLanguage } from '../../lib/language';

type Dashboard = { completedLessons: number; xp: number; certificates: { verificationId: string }[]; achievements: { achievement: { name: string; description: string; badge: string } }[]; enrollments: { course?: { id: string; title: string; description: string } }[] };
const api = process.env.NEXT_PUBLIC_API_URL || '/api/v1';
const copy = {
  en: { required: 'Sign in is required.', failed: 'Dashboard could not be loaded.', title: 'Continue learning.', intro: 'Your progress, courses, and certificates in one place.', loading: 'Loading dashboard…', signIn: 'Sign in', active: 'Active courses', completed: 'Completed lessons', xp: 'XP earned', mine: 'My courses', explore: 'Explore courses →', course: 'Course', practical: 'Continue your practical lessons.', continue: 'Continue →', start: 'Start learning', none: 'You have not enrolled in a course yet.', certificates: 'Certificates', certText: 'Complete courses to earn certificates.', achievements: 'Achievements', achievementText: 'Your first achievement unlocks when you complete a course.' },
  fa: { required: 'برای ادامه وارد حساب شوید.', failed: 'داشبورد بارگذاری نشد.', title: 'یادگیری را ادامه دهید.', intro: 'پیشرفت، دوره‌ها و گواهی‌نامه‌های شما در یک جا.', loading: 'داشبورد در حال بارگذاری است…', signIn: 'ورود', active: 'دوره‌های فعال', completed: 'درس‌های تکمیل‌شده', xp: 'امتیاز XP', mine: 'دوره‌های من', explore: 'مشاهده دوره‌ها →', course: 'دوره', practical: 'درس‌های عملی خود را ادامه دهید.', continue: 'ادامه →', start: 'یادگیری را آغاز کنید', none: 'هنوز در دوره‌ای ثبت‌نام نکرده‌اید.', certificates: 'گواهی‌نامه‌ها', certText: 'دوره‌ها را تمام کنید و گواهی بگیرید.', achievements: 'دستاوردها', achievementText: 'نخستین دستاورد شما پس از پایان یک دوره باز می‌شود.' },
  ps: { required: 'د دوام لپاره ننوځئ.', failed: 'ډشبورډ پورته نه شو.', title: 'زده‌کړې ته دوام ورکړئ.', intro: 'ستاسو پرمختګ، کورسونه او سندونه په یوه ځای کې.', loading: 'ډشبورډ پورته کېږي…', signIn: 'ننوتل', active: 'فعال کورسونه', completed: 'بشپړ شوي درسونه', xp: 'ترلاسه شوی XP', mine: 'زما کورسونه', explore: 'کورسونه وګورئ →', course: 'کورس', practical: 'خپلو عملي درسونو ته دوام ورکړئ.', continue: 'دوام →', start: 'زده‌کړه پیل کړئ', none: 'تاسو تر اوسه په کوم کورس کې نوم‌لیکنه نه ده کړې.', certificates: 'سندونه', certText: 'کورسونه بشپړ کړئ او سندونه ترلاسه کړئ.', achievements: 'لاسته راوړنې', achievementText: 'ستاسو لومړۍ لاسته راوړنه د کورس تر بشپړولو وروسته پرانیستل کېږي.' }
};

export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const { language } = useLanguage(); const c = copy[language];
  useEffect(() => { const token = sessionStorage.getItem('afghan-it.access-token'); if (!token) { setError(c.required); setLoading(false); return; } fetch(`${api}/dashboard`, { headers: { authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : Promise.reject(new Error(c.failed))).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [c.required, c.failed]);
  return <main><SiteHeader /><section className="dashboard-hero"><span className="section-kicker">Learner dashboard</span><h1>{c.title}</h1><p>{c.intro}</p></section>{loading && <p className="page-state">{c.loading}</p>}{error && <section className="page-state"><p>{error}</p><Link className="primary-button" href="/login">{c.signIn}</Link></section>}{data && <section className="dashboard dashboard-content"><div className="stats"><div className="stat"><strong>{data.enrollments.length}</strong>{c.active}</div><div className="stat"><strong>{data.completedLessons}</strong>{c.completed}</div><div className="stat"><strong>{data.xp}</strong>{c.xp}</div></div><div className="dashboard-columns"><div><div className="section-title"><h2>{c.mine}</h2><Link href="/courses">{c.explore}</Link></div>{data.enrollments.length ? data.enrollments.map((item, index) => <article className="dashboard-course" key={item.course?.id || index}><div className="course-icon">{String(index + 1).padStart(2, '0')}</div><div><h3>{item.course?.title || c.course}</h3><p>{item.course?.description || c.practical}</p></div>{item.course?.id && <Link href={`/courses/${item.course.id}`}>{c.continue}</Link>}</article>) : <div className="empty-state"><h3>{c.start}</h3><p>{c.none}</p><Link className="primary-button" href="/courses">{c.explore}</Link></div>}</div><aside><div className="dashboard-side"><h3>{c.certificates}</h3><strong>{data.certificates.length}</strong><p>{c.certText}</p>{data.certificates.map(cert => <a key={cert.verificationId} href={`/api/v1/certificates/verify/${cert.verificationId}`} target="_blank" rel="noreferrer">{cert.verificationId} ↗</a>)}</div><div className="dashboard-side"><h3>{c.achievements}</h3>{data.achievements.length ? data.achievements.map(({ achievement }) => <div className="achievement" key={achievement.name}><span>{achievement.badge}</span><div><b>{achievement.name}</b><small>{achievement.description}</small></div></div>) : <p>{c.achievementText}</p>}</div></aside></div></section>}</main>;
}
