'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type Dashboard = { completedLessons: number; xp: number; certificates: { verificationId: string; issuedAt: string }[]; assessmentAttempts: { score: number; passed: boolean }[]; achievements: { achievement: { name: string; description: string; badge: string } }[]; enrollments: { course?: { id: string; title: string; description: string } }[] };
const api = process.env.NEXT_PUBLIC_API_URL || '/api/v1';
export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const token = sessionStorage.getItem('afghan-it.access-token'); if (!token) { setError('Kirish talab qilinadi.'); setLoading(false); return; } fetch(`${api}/dashboard`, { headers: { authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : Promise.reject(new Error('Dashboard yuklanmadi'))).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  function signOut() { sessionStorage.removeItem('afghan-it.access-token'); window.location.assign('/login'); }
  return <main><header className="masthead"><Link className="brand" href="/"><span className="brand-mark">◆</span><span>Afghan IT<small>Academy</small></span></Link><nav><Link href="/courses">Kurslar</Link><Link href="/mentor">AI Mentor</Link></nav><div className="header-actions"><Link className="outline-button" href="/">Bosh sahifa</Link><button className="language" onClick={signOut}>Chiqish</button></div></header><section className="dashboard-hero"><span className="section-kicker">Learner dashboard</span><h1>O‘qishni davom ettiring.</h1><p>Progressingiz, kurslaringiz va sertifikatlaringiz bir joyda.</p></section>{loading && <p className="page-state">Dashboard yuklanmoqda…</p>}{error && <section className="page-state"><p>{error}</p><Link className="primary-button" href="/login">Kirish</Link></section>}{data && <><section className="dashboard dashboard-content"><div className="stats"><div className="stat"><strong>{data.enrollments.length}</strong>Faol kurslar</div><div className="stat"><strong>{data.completedLessons}</strong>Tugallangan darslar</div><div className="stat"><strong>{data.xp}</strong>Yig‘ilgan XP</div></div><div className="dashboard-columns"><div><div className="section-title"><h2>Mening kurslarim</h2><Link href="/courses">Kurslarni ko‘rish →</Link></div>{data.enrollments.length ? data.enrollments.map((item, index) => <article className="dashboard-course" key={item.course?.id || index}><div className="course-icon">{String(index + 1).padStart(2, '0')}</div><div><h3>{item.course?.title || 'Kurs'}</h3><p>{item.course?.description || 'Amaliy darslarni davom ettiring.'}</p></div>{item.course?.id && <Link href={`/courses/${item.course.id}`}>Davom etish →</Link>}</article>) : <div className="empty-state"><h3>O‘qishni boshlang</h3><p>Siz hali kursga yozilmagansiz.</p><Link className="primary-button" href="/courses">Kurslarni ko‘rish</Link></div>}</div><aside><div className="dashboard-side"><h3>Sertifikatlar</h3><strong>{data.certificates.length}</strong><p>Kurslarni tugatib, sertifikat oling.</p>{data.certificates.map(c => <a key={c.verificationId} href={`/api/v1/certificates/verify/${c.verificationId}`} target="_blank" rel="noreferrer">{c.verificationId} ↗</a>)}</div><div className="dashboard-side"><h3>Yutuqlar</h3>{data.achievements.length ? data.achievements.map(({ achievement }) => <div className="achievement" key={achievement.name}><span>{achievement.badge}</span><div><b>{achievement.name}</b><small>{achievement.description}</small></div></div>) : <p>Ilk yutug‘ingiz kursni tugatgach ochiladi.</p>}</div></aside></div></section></>}</main>;
}
