import { pgEnum, pgTable, text, timestamp, uuid, boolean, integer, jsonb, uniqueIndex, primaryKey } from 'drizzle-orm/pg-core';

export const roleEnum = pgEnum('role', ['student', 'teacher', 'admin', 'super_admin']);
export const lessonTypeEnum = pgEnum('lesson_type', ['video', 'text', 'quiz', 'practical', 'exam']);
export const enrollmentStatusEnum = pgEnum('enrollment_status', ['active', 'completed', 'cancelled']);

export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(), email: text('email').notNull(), name: text('name').notNull(),
  passwordHash: text('password_hash').notNull(), preferredLocale: text('preferred_locale').notNull().default('en'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('users_email_idx').on(t.email)]);

export const refreshTokens = pgTable('refresh_tokens', {
  id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  tokenHash: text('token_hash').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), revokedAt: timestamp('revoked_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const roles = pgTable('roles', { userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), role: roleEnum('role').notNull() }, (t) => [primaryKey({ columns: [t.userId, t.role] })]);
export const tenants = pgTable('tenants', { id: uuid('id').defaultRandom().primaryKey(), slug: text('slug').notNull(), name: text('name').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex('tenants_slug_idx').on(t.slug)]);
export const tenantMemberships = pgTable('tenant_memberships', { tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), role: roleEnum('role').notNull().default('student') }, (t) => [primaryKey({ columns: [t.tenantId, t.userId] })]);

export const courses = pgTable('courses', { id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').references(() => tenants.id, { onDelete: 'set null' }), slug: text('slug').notNull(), title: text('title').notNull(), description: text('description').notNull().default(''), category: text('category').notNull(), language: text('language').notNull().default('en'), translations: jsonb('translations').notNull().default({}), level: text('level').notNull().default('beginner'), coverUrl: text('cover_url'), published: boolean('published').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex('courses_slug_idx').on(t.slug)]);
export const modules = pgTable('modules', { id: uuid('id').defaultRandom().primaryKey(), courseId: uuid('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), title: text('title').notNull(), position: integer('position').notNull().default(0) });
export const lessons = pgTable('lessons', { id: uuid('id').defaultRandom().primaryKey(), moduleId: uuid('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }), title: text('title').notNull(), type: lessonTypeEnum('type').notNull().default('video'), content: text('content').notNull().default(''), position: integer('position').notNull().default(0), durationMinutes: integer('duration_minutes').notNull().default(10) });
export const enrollments = pgTable('enrollments', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), courseId: uuid('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), status: enrollmentStatusEnum('status').notNull().default('active'), enrolledAt: timestamp('enrolled_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex('enrollments_user_course_idx').on(t.userId, t.courseId)]);
export const lessonProgress = pgTable('lesson_progress', { userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), lessonId: uuid('lesson_id').notNull().references(() => lessons.id, { onDelete: 'cascade' }), completed: boolean('completed').notNull().default(false), percent: integer('percent').notNull().default(0), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [primaryKey({ columns: [t.userId, t.lessonId] })]);
export const certificates = pgTable('certificates', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), courseId: uuid('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), verificationId: text('verification_id').notNull(), issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex('certificates_verification_idx').on(t.verificationId)]);
export const xpEvents = pgTable('xp_events', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), amount: integer('amount').notNull(), reason: text('reason').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() });
export const plans = pgTable('plans', { id: uuid('id').defaultRandom().primaryKey(), slug: text('slug').notNull(), name: text('name').notNull(), priceCents: integer('price_cents').notNull().default(0), currency: text('currency').notNull().default('USD'), features: jsonb('features').notNull().default([]) }, (t) => [uniqueIndex('plans_slug_idx').on(t.slug)]);
export const subscriptions = pgTable('subscriptions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), planId: uuid('plan_id').notNull().references(() => plans.id), status: text('status').notNull().default('active'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() });
