'use client';

import { FormEvent, useEffect, useState } from 'react';
import { SiteHeader } from '../../components/site-header';
import { authFetch } from '../../lib/api';
import { useLanguage } from '../../lib/language';

const api = process.env.NEXT_PUBLIC_API_URL || '/api/v1';
type Summary = { courses: number; learners: number; enrollments: number };
type Course = { id: string; title: string; slug: string; published: boolean };
const copy = {
  en: { eyebrow: 'Teacher studio', title: 'Build learning that learners can finish.', intro: 'Create structured courses, modules, and lessons. Only teacher and administrator accounts can publish content.', courses: 'courses', learners: 'learners', enrollments: 'enrollments', required: 'Sign in with a teacher account to see the teaching dashboard.', roster: 'Course roster', published: 'published', draft: 'draft', view: 'View learners', new: 'New course draft', name: 'Title', slug: 'URL slug', category: 'Category', description: 'Description', create: 'Create draft', created: 'Draft course created.', denied: 'Teacher access is required.' },
  fa: { eyebrow: 'استودیوی استاد', title: 'آموزشی بسازید که دانشجویان بتوانند تمام کنند.', intro: 'دوره‌ها، بخش‌ها و درس‌های منظم بسازید. تنها استاد و مدیر می‌توانند محتوا منتشر کنند.', courses: 'دوره', learners: 'دانشجو', enrollments: 'ثبت‌نام', required: 'با حساب استاد وارد شوید.', roster: 'فهرست دوره‌ها', published: 'منتشرشده', draft: 'پیش‌نویس', view: 'دیدن دانشجویان', new: 'پیش‌نویس دوره جدید', name: 'عنوان', slug: 'نشانی URL', category: 'دسته‌بندی', description: 'توضیحات', create: 'ساخت پیش‌نویس', created: 'پیش‌نویس ساخته شد.', denied: 'دسترسی استاد لازم است.' },
  ps: { eyebrow: 'د ښوونکي سټوډیو', title: 'داسې زده‌کړه جوړه کړئ چې زده‌کوونکي یې بشپړه کړي.', intro: 'منظم کورسونه، برخې او درسونه جوړ کړئ. یوازې ښوونکي او مدیران منځپانګه خپرولی شي.', courses: 'کورسونه', learners: 'زده‌کوونکي', enrollments: 'نوم‌لیکنې', required: 'د ښوونکي حساب سره ننوځئ.', roster: 'د کورسونو لړ', published: 'خپور شوی', draft: 'مسوده', view: 'زده‌کوونکي وګورئ', new: 'د نوي کورس مسوده', name: 'سرلیک', slug: 'URL نوم', category: 'ډله', description: 'تشریح', create: 'مسوده جوړه کړئ', created: 'مسوده جوړه شوه.', denied: 'د ښوونکي لاسرسی اړین دی.' }
};

export default function TeacherPage() {
  const { language } = useLanguage(); const c = copy[language]; const [summary, setSummary] = useState<Summary | null>(null); const [courses, setCourses] = useState<Course[]>([]); const [learners, setLearners] = useState<{ learner: { name: string; email: string }; enrollment: { status: string } }[]>([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ title: '', slug: '', category: 'IT', description: '' });
  useEffect(() => { authFetch(`${api}/teacher/dashboard`).then(response => response.ok ? response.json() : null).then(setSummary); authFetch(`${api}/teacher/courses`).then(response => response.ok ? response.json() : []).then(setCourses); }, []);
  async function showLearners(courseId: string) { const response = await authFetch(`${api}/teacher/courses/${courseId}/learners`); setLearners(response.ok ? await response.json() : []); }
  async function createCourse(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await authFetch(`${api}/teacher/courses`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, published: false }) }); setMessage(response.ok ? c.created : c.denied); if (response.ok) setForm({ title: '', slug: '', category: 'IT', description: '' }); }
  return <main><SiteHeader /><section className="hero"><div className="eyebrow">{c.eyebrow}</div><h1>{c.title}</h1><p>{c.intro}</p></section>{summary ? <div className="stats"><div className="stat"><strong>{summary.courses}</strong>{c.courses}</div><div className="stat"><strong>{summary.learners}</strong>{c.learners}</div><div className="stat"><strong>{summary.enrollments}</strong>{c.enrollments}</div></div> : <p className="notice">{c.required}</p>}<section className="learning-module"><div className="section-title"><h2>{c.roster}</h2></div>{courses.map(course => <div className="lesson" key={course.id}><div><strong>{course.title}</strong><small>{course.slug} · {course.published ? c.published : c.draft}</small></div><button className="quiet" onClick={() => showLearners(course.id)}>{c.view}</button></div>)}{learners.map(({ learner, enrollment }) => <div className="lesson" key={learner.email}><div><strong>{learner.name}</strong><small>{learner.email}</small></div><small>{enrollment.status}</small></div>)}</section><section className="login"><div className="section-title"><h2>{c.new}</h2></div><form onSubmit={createCourse}><label>{c.name}<input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} required /></label><label>{c.slug}<input value={form.slug} onChange={event => setForm({ ...form, slug: event.target.value })} required /></label><label>{c.category}<input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} required /></label><label>{c.description}<input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><button>{c.create}</button></form><p className="notice">{message}</p></section></main>;
}
