'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useLanguage } from '../../lib/language';
import { setAccessToken } from '../../lib/api';

const api = process.env.NEXT_PUBLIC_API_URL || '/api/v1';
const copy = {
  en: { invalid: 'Incorrect email or password.', server: 'Could not connect to the server. Please try again.', home: 'Home', registerTitle: 'Start learning.', welcome: 'Welcome back.', registerIntro: 'Create an account and access practical courses.', loginIntro: 'Sign in to continue learning.', promise1: 'Video lessons, assessments, and practical tasks', promise2: 'Certificates and AI Mentor support', create: 'Create account', signIn: 'Sign in', name: 'Full name', password: 'Password', busy: 'Please wait…', have: 'Already have an account?', need: 'Need an account?', register: 'Register' },
  fa: { invalid: 'ایمیل یا رمز عبور نادرست است.', server: 'ارتباط با سرور برقرار نشد. دوباره تلاش کنید.', home: 'صفحه اصلی', registerTitle: 'یادگیری را آغاز کنید.', welcome: 'خوش آمدید.', registerIntro: 'حساب بسازید و به دوره‌های عملی دسترسی بگیرید.', loginIntro: 'برای ادامه یادگیری وارد حساب شوید.', promise1: 'درس‌های ویدیویی، آزمون‌ها و تمرین‌های عملی', promise2: 'گواهی‌نامه و پشتیبانی مربی هوش مصنوعی', create: 'ساخت حساب', signIn: 'ورود', name: 'نام کامل', password: 'رمز عبور', busy: 'لطفاً منتظر بمانید…', have: 'حساب دارید؟', need: 'هنوز حساب ندارید؟', register: 'ثبت‌نام' },
  ps: { invalid: 'ایمیل یا پټنوم ناسم دی.', server: 'له سرور سره اړیکه ونه نیول شوه. بیا هڅه وکړئ.', home: 'کورپاڼه', registerTitle: 'زده‌کړه پیل کړئ.', welcome: 'ښه راغلاست.', registerIntro: 'حساب جوړ کړئ او عملي کورسونو ته لاسرسی ومومئ.', loginIntro: 'د زده‌کړې د دوام لپاره ننوځئ.', promise1: 'ویډیويي درسونه، ازموینې او عملي دندې', promise2: 'سندونه او د AI لارښود مرسته', create: 'حساب جوړ کړئ', signIn: 'ننوتل', name: 'بشپړ نوم', password: 'پټنوم', busy: 'لږ انتظار وکړئ…', have: 'حساب لرئ؟', need: 'تر اوسه حساب نه لرئ؟', register: 'نوم‌لیکنه' }
};

export default function LoginPage() {
  const router = useRouter(); const { language } = useLanguage(); const c = copy[language];
  const [registering, setRegistering] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { setRegistering(new URLSearchParams(window.location.search).get('register') === '1'); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`${api}/auth/${registering ? 'register' : 'login'}`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(registering ? { name, email, password, preferredLocale: language } : { email, password }) }); const data = await response.json().catch(() => ({})) as { accessToken?: string; message?: string }; if (!response.ok || !data.accessToken) { setError(Array.isArray(data.message) ? data.message.join(' ') : data.message || c.invalid); return; } setAccessToken(data.accessToken); router.push('/dashboard'); } catch { setError(c.server); } finally { setBusy(false); } }
  return <main className="auth-shell"><header className="auth-header"><Link className="brand" href="/"><span className="brand-mark">◆</span><span>Afghan IT<small>Academy</small></span></Link><Link href="/">{c.home}</Link></header><section className="auth-card"><div className="auth-intro"><span className="eyebrow">Afghan IT Academy</span><h1>{registering ? c.registerTitle : c.welcome}</h1><p>{registering ? c.registerIntro : c.loginIntro}</p><div className="auth-promise"><b>✓</b><span>{c.promise1}</span><b>✓</b><span>{c.promise2}</span></div></div><form className="auth-form" onSubmit={submit}><h2>{registering ? c.create : c.signIn}</h2>{registering && <label>{c.name}<input value={name} onChange={e => setName(e.target.value)} required autoComplete="name" /></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="email" /></label><label>{c.password}<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} autoComplete={registering ? 'new-password' : 'current-password'} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={busy}>{busy ? c.busy : registering ? c.create : c.signIn}</button><p className="auth-switch">{registering ? c.have : c.need} <button type="button" onClick={() => setRegistering(!registering)}>{registering ? c.signIn : c.register}</button></p></form></section></main>;
}
