'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

const api = process.env.NEXT_PUBLIC_API_URL || '/api/v1';

export default function LoginPage() {
  const router = useRouter();
  const [registering, setRegistering] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { setRegistering(new URLSearchParams(window.location.search).get('register') === '1'); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`${api}/auth/${registering ? 'register' : 'login'}`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(registering ? { name, email, password, preferredLocale: 'uz' } : { email, password }) }); const data = await response.json().catch(() => ({})) as { accessToken?: string; message?: string }; if (!response.ok || !data.accessToken) { setError(Array.isArray(data.message) ? data.message.join(' ') : data.message || 'Email yoki parol noto‘g‘ri.'); return; } sessionStorage.setItem('afghan-it.access-token', data.accessToken); router.push('/dashboard'); } catch { setError('Server bilan bog‘lanib bo‘lmadi. Qayta urinib ko‘ring.'); } finally { setBusy(false); } }
  return <main className="auth-shell"><header className="auth-header"><Link className="brand" href="/"><span className="brand-mark">◆</span><span>Afghan IT<small>Academy</small></span></Link><Link href="/">Bosh sahifa</Link></header><section className="auth-card"><div className="auth-intro"><span className="eyebrow">Afghan IT Academy</span><h1>{registering ? 'O‘qishni boshlang.' : 'Xush kelibsiz.'}</h1><p>{registering ? 'Hisob yarating va amaliy kurslarga kirish oling.' : 'O‘qishni davom ettirish uchun hisobingizga kiring.'}</p><div className="auth-promise"><b>✓</b><span>Video darslar, testlar va amaliy vazifalar</span><b>✓</b><span>Sertifikat va AI Mentor yordami</span></div></div><form className="auth-form" onSubmit={submit}><h2>{registering ? 'Hisob yaratish' : 'Kirish'}</h2>{registering && <label>To‘liq ism<input value={name} onChange={e => setName(e.target.value)} required autoComplete="name" /></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="email" /></label><label>Parol<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} autoComplete={registering ? 'new-password' : 'current-password'} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={busy}>{busy ? 'Tekshirilmoqda…' : registering ? 'Hisob yaratish' : 'Kirish'}</button><p className="auth-switch">{registering ? 'Hisobingiz bormi?' : 'Hali hisobingiz yo‘q?'} <button type="button" onClick={() => setRegistering(!registering)}>{registering ? 'Kirish' : 'Ro‘yxatdan o‘tish'}</button></p></form></section></main>;
}
