'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';

export function SiteHeader() {
  const [signedIn, setSignedIn] = useState(false); const [language, setLanguage] = useState('fa'); const [languageOpen, setLanguageOpen] = useState(false); const languageRef = useRef<HTMLDivElement>(null);
  useEffect(() => { setSignedIn(Boolean(sessionStorage.getItem('afghan-it.access-token'))); setLanguage(localStorage.getItem('afghan-it.language') || 'fa'); }, []);
  useEffect(() => { const close = (event: MouseEvent) => { if (!languageRef.current?.contains(event.target as Node)) setLanguageOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  function changeLanguage(value: string) { setLanguage(value); setLanguageOpen(false); localStorage.setItem('afghan-it.language', value); document.documentElement.lang = value; }
  const languageName = language === 'ps' ? 'Pashto' : language === 'en' ? 'English' : 'Dari';
  return <header className="masthead"><Link className="brand" href="/"><span className="brand-mark">◆</span><span>Afghan IT<small>Academy</small></span></Link><nav><Link href="/courses">Kurslar</Link><Link href="/courses?category=it">IT yo‘nalishlar</Link><Link href="/courses?category=english">Ingliz tili</Link><Link href="/mentor">AI Mentor</Link><a href="/#footer">Biz haqimizda</a></nav><div className="header-actions"><button className="search" aria-label="Search">⌕</button><div className="language-select" ref={languageRef}><button className="language-select-trigger" type="button" aria-haspopup="listbox" aria-expanded={languageOpen} onClick={() => setLanguageOpen(!languageOpen)}><span className="language-label">Til</span><strong>{languageName}</strong><b className="language-chevron">⌄</b></button>{languageOpen && <div className="language-menu" role="listbox" aria-label="Tilni tanlang"><button type="button" role="option" aria-selected={language === 'fa'} onClick={() => changeLanguage('fa')}><span>دری</span><strong>Dari</strong>{language === 'fa' && <b>✓</b>}</button><button type="button" role="option" aria-selected={language === 'ps'} onClick={() => changeLanguage('ps')}><span>پښتو</span><strong>Pashto</strong>{language === 'ps' && <b>✓</b>}</button><button type="button" role="option" aria-selected={language === 'en'} onClick={() => changeLanguage('en')}><span>EN</span><strong>English</strong>{language === 'en' && <b>✓</b>}</button></div>}</div>{signedIn ? <Link className="header-button" href="/account">Mening hisobim</Link> : <><Link className="outline-button" href="/login">Kirish</Link><Link className="header-button" href="/login?register=1">Ro‘yxatdan o‘tish</Link></>}</div></header>;
}
