'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useLanguage } from '../lib/language';

export function SiteHeader() {
  const [signedIn, setSignedIn] = useState(false); const [languageOpen, setLanguageOpen] = useState(false); const languageRef = useRef<HTMLDivElement>(null); const { language, changeLanguage } = useLanguage();
  useEffect(() => { setSignedIn(Boolean(sessionStorage.getItem('afghan-it.access-token'))); }, []);
  useEffect(() => { const close = (event: MouseEvent) => { if (!languageRef.current?.contains(event.target as Node)) setLanguageOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  const languageName = language === 'ps' ? 'Pashto' : language === 'en' ? 'English' : 'Dari';
  const labels = { fa: ['دوره‌ها', 'مسیرهای آی‌تی', 'دوره‌های انگلیسی', 'مربی هوش مصنوعی', 'درباره ما', 'ورود', 'ثبت‌نام', 'حساب من'], ps: ['کورسونه', 'د آی‌ټي لارې', 'د انګلیسي کورسونه', 'AI لارښود', 'زموږ په اړه', 'ننوتل', 'نوم‌لیکنه', 'زما حساب'], en: ['Courses', 'IT paths', 'English courses', 'AI Mentor', 'About us', 'Sign in', 'Register', 'My account'] }[language];
  return <header className="masthead"><Link className="brand" href="/"><span className="brand-mark">◆</span><span>Afghan IT<small>Academy</small></span></Link><nav><Link href="/courses">{labels[0]}</Link><Link href="/courses?category=it">{labels[1]}</Link><Link href="/courses?category=english">{labels[2]}</Link><Link href="/mentor">{labels[3]}</Link><a href="/#footer">{labels[4]}</a></nav><div className="header-actions"><button className="search" aria-label="Search">⌕</button><div className="language-select" ref={languageRef}><button className="language-select-trigger" type="button" aria-haspopup="listbox" aria-expanded={languageOpen} onClick={() => setLanguageOpen(!languageOpen)}><span className="language-label">{language === 'fa' ? 'زبان' : language === 'ps' ? 'ژبه' : 'Language'}</span><strong>{languageName}</strong><b className="language-chevron">⌄</b></button>{languageOpen && <div className="language-menu" role="listbox" aria-label="Choose language"><button type="button" role="option" aria-selected={language === 'fa'} onClick={() => { changeLanguage('fa'); setLanguageOpen(false); }}><span>دری</span><strong>Dari</strong>{language === 'fa' && <b>✓</b>}</button><button type="button" role="option" aria-selected={language === 'ps'} onClick={() => { changeLanguage('ps'); setLanguageOpen(false); }}><span>پښتو</span><strong>Pashto</strong>{language === 'ps' && <b>✓</b>}</button><button type="button" role="option" aria-selected={language === 'en'} onClick={() => { changeLanguage('en'); setLanguageOpen(false); }}><span>EN</span><strong>English</strong>{language === 'en' && <b>✓</b>}</button></div>}</div>{signedIn ? <Link className="header-button" href="/account">{labels[7]}</Link> : <><Link className="outline-button" href="/login">{labels[5]}</Link><Link className="header-button" href="/login?register=1">{labels[6]}</Link></>}</div></header>;
}
